version: '3.9'
services:
  localstack: # LocalStack container
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      # Map the port so you can access the API from the host machine
      - 4566:4566
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      # Here you mount your setup file so it will be executed
      # when the container starts
      # - ./init:/etc/localstack/init/ready.d
      - /var/run/docker.sock:/var/run/docker.sock